// ============================================================================
// Version.h - GENERATED FILE - DO NOT EDIT
// ============================================================================
// Project: ASA-EMulatR - Alpha AXP Architecture Emulator
// Copyright (C) 2025 eNVy Systems, Inc. All rights reserved.
// Licensed under eNVy Systems Non-Commercial License v1.1
//
// Project Architect: Timothy Peer
// AI Code Generation: Claude (Anthropic) / ChatGPT (OpenAI)
//
// Commercial use prohibited without separate license.
// Contact: peert@envysys.com | https://envysys.com
// Documentation: https://timothypeer.github.io/ASA-EMulatR-Project/
// ============================================================================

// ============================================================================
// Version.h - GENERATED FILE - DO NOT EDIT
// Generated by CMake from Version.h.in
// ============================================================================

#ifndef EMULATR_VERSION_H
#define EMULATR_VERSION_H

#pragma once

#include <QtGlobal>
#include <QString>

namespace EmulatR {

// ============================================================================
// Version Information (injected by CMake)
// ============================================================================

constexpr int VERSION_MAJOR = 0;
constexpr int VERSION_MINOR = 9;
constexpr int VERSION_PATCH = 0;
constexpr quint32 BUILD_DATE = 20260130;
constexpr quint32 BUILD_NUMBER = 0;

#define EMULATR_VERSION "0.9.0"
#define EMULATR_VERSION_STRING "0.9.0"
#define EMULATR_GIT_HASH "-dirty"
#define EMULATR_GIT_BRANCH ""
#define EMULATR_BUILD_CONFIG "Debug"
#define EMULATR_PLATFORM "Windows"
#define EMULATR_COMPILER "MSVC 19.44.35215.0"
#define EMULATR_BUILD_TIMESTAMP "2026-01-30 19:40:13 UTC"

// ============================================================================
// Runtime Version Functions
// ============================================================================

inline QString getVersionString() noexcept
{
    return QString("%1.%2.%3")
        .arg(VERSION_MAJOR)
        .arg(VERSION_MINOR)
        .arg(VERSION_PATCH);
}

inline QString getFullVersionString() noexcept
{
    return QString("%1 (Build %2, %3, %4)")
        .arg(EMULATR_VERSION)
        .arg(BUILD_NUMBER)
        .arg(EMULATR_BUILD_CONFIG)
        .arg(EMULATR_PLATFORM);
}

inline QString getBuildInfo() noexcept
{
    return QString("Built: %1 | Git: %2@%3 | Compiler: %4")
        .arg(EMULATR_BUILD_TIMESTAMP)
        .arg(EMULATR_GIT_BRANCH)
        .arg(EMULATR_GIT_HASH)
        .arg(EMULATR_COMPILER);
}

inline QString getVersionAndBuild() noexcept
{
    return QString("ASA EmulatR %1 (Build %2)")
        .arg(EMULATR_VERSION)
        .arg(BUILD_NUMBER);
}

} // namespace EmulatR

#endif // EMULATR_VERSION_H
