#ifndef CONTROLLERSLIB_GLOBAL_H
#define CONTROLLERSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERSLIB_LIBRARY)
#define CONTROLLERSLIB_EXPORT Q_DECL_EXPORT
#else
#define CONTROLLERSLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERSLIB_GLOBAL_H
