#ifndef GRAINFACTORYLIB_GLOBAL_H
#define GRAINFACTORYLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAINFACTORYLIB_LIBRARY)
#define GRAINFACTORYLIB_EXPORT Q_DECL_EXPORT
#else
#define GRAINFACTORYLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAINFACTORYLIB_GLOBAL_H
