#ifndef MACHINELIB_GLOBAL_H
#define MACHINELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MACHINELIB_LIBRARY)
#define MACHINELIB_EXPORT Q_DECL_EXPORT
#else
#define MACHINELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MACHINELIB_GLOBAL_H
