#ifndef CPUCORELIB_GLOBAL_H
#define CPUCORELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPUCORELIB_LIBRARY)
#define CPUCORELIB_EXPORT Q_DECL_EXPORT
#else
#define CPUCORELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CPUCORELIB_GLOBAL_H
